### PR TITLE
Support leaf_off_flag from land_cover_data for TMF methodology

### PR DESCRIPTION
**Pull request by mdales**

### CODE REVIEW

**Review by ameliaholcomb — APPROVED** [review]
LGTM

**Comment by mdales** [comment]
Before I merge this one @ameliaholcomb, this one will potentially cause issues if we don't add the column to your database if you import new databases - are you okay with that?

**Comment by ameliaholcomb** [comment]
Ahhh, sorry I didn't catch that when I was reviewing. Yeah, I don't love doing this without adding the column to the DB, and ideally even backfilling on existing rows (though I know that's a lot of work). 

Now that I think about it, what do you need the leaf_off_flag for? The l4_quality_flag requires that leaf_off_flag == 0, and I'm assuming you already filter by that in your L4A code? Let's only pursue this change if you're making use of L4A shots with l4_quality_flag == 0 && leaf_off_flag == 1

**Comment by mdales** [comment]
As per the comment from @ameliaholcomb, we're already filtering on l4_quality_flag, and so for now I'll close this one.

**Pull request closed without merging**
